### ISSUE TITLE
Verify preferredDomain with hostDomain for Google authentication's

### ISSUE THREAD

**Issue by fsilvestre** [vouch/vouch-proxy#127]
I'm tried to figured out why Vouch isn't validating host domain from Google users.
When i set preferred domain, i got the box of username prefilled with @domain.com but it still allow users to use their @gmail.com or another mail domain hosted by Google, allowing them to authenticate against the system.
Said that, i'm looked for a way to do it with HostDomain information and to use it i added hd for User struct, but i don't like that since that can cause problems for other future authentication gateways.
So, i used the substring to validate the domain under function VerifyUser as this:
`  // TODO: how do we manage the user?
  user := u.(structs.User)

  userdomain := strings.Split(user.Email, "@")[1]

  if cfg.GenOAuth.Provider == cfg.Providers.Google && len(cfg.GenOAuth.PreferredDomain) != 0 && cfg.GenOAuth.PreferredDomain != userdomain {
    err = fmt.Errorf("Access restricted for domain users")
    return ok, err
  }
`

Are that the right way to get the domain validation?

**Comment by bnfinet** [comment]
@fsilvestre did you set `vouch.domains` to the same domain you set as the `oauth.preferredDomain` as per...
https://github.com/vouch/vouch-proxy/blob/master/config/config.yml_example_google 

If you'd like further support please follow the instructions in the README regarding posting your redacted configs.  Without your configs and logs its difficult to understand the expected behavior and what you're actually seeing.

If you're modifying the codebase, please provide access to the source code

**Comment by bnfinet** [comment]
@fsilvestre I'm going to close this issue, please do reach out if you'd like to reopen
