### ISSUE TITLE
How to get Vouch Proxy to work with homegrown local OAuth service

### ISSUE THREAD

**Issue by redm123** [vouch/vouch-proxy#144]
Hi

I'm trying to get vouch-proxy to work with some homegrown local OAuth service. Went through the docs a couple of times, looked through reports here, tried this and that. But no success so far. Meanwhile I'm starting to think that either I'm missing the obvious or my use case/our OAuth service is (currently) simply not supported.

See vouch config, nginx config, logs at https://hasteb.in/ivepiwev.yaml

Some identifiers used:
local homegrown Oauth service: `api.foobar.com`
Vouch proxy: `vouch.example.com`
Protected web application: `myapp.example.com`
client_id: `<MY_CLIENT_ID>`
client_secret: `<MY_CLIENT_SECRET>`

I first tried with "oidc" provider, but that dies with 
`2019-08-15T15:00:15.743Z        ERROR   http: panic serving 172.17.0.2:56372: interface conversion: interface {} is nil, not string
`
see hasteb.in:198

Maybe because our OAuth service does not really have a "userinfo" endpoint...? (I used something else instead, but I'm not sure vouch-proxy ever tries to call it)

Then I tried "adfs" provider (whatever that is, read it in some ticket here). This seems to get me a little further. 

First problem was that it always put the cookie into `vouch.example.com` domain, and of course it got not sent when accessing `myapp.example.com` again, getting in an endless validation loop. Not sure if there is something wrong in my config in the first place, but I was eventually able to fix that by forcing the domain to `example.com`.

But now it fails with `no Username found in jwt`. Well, yea... there is none... not sure where this is should come from...

The only thing that delivers something like a user name here is the /token endpoint. But it seems never called by vouch-proxy. And even if, would it return me the data inside?? What it returns looks something like this:

`
{
"access_token":"fffffffffffff",
"token_type":"Bearer",
"refresh_token":"xxxxxxxxxxxxxxxx",
"expires_in":3600,
"account_key":"6666666666666",
"account_type":"",
"email":"foo.bar@example.com",
"firstName":"Foo",
"lastName":"Bar",
"hello_key":"1234567890",
"version":"3"
}
`

Any help appreciated :)

Thanks

Michael

**Comment by artagel** [comment]
In order for vouch to support a home-grown oauth provider that doesn't conform to a standard (like oidc), you'd need to add code to support that provider, ensure the user data can be gotten fro the right place, etc.  

If you look at line 533 in[ handlers.go](https://github.com/vouch/vouch-proxy/blob/master/handlers/handlers.go#L533) you'll see the code is choosing which user function to call depending on the provider, as they do it differently.  ADFS is for Active Directory Federated Services (Microsoft Active Directory), but it still pretty much uses OIDC, but does something special with the user info.  Essentially, vouch *requires* the user info so it can keep track of the user and issue the JWT properly, so code would need to be added to support your oauth provider so properly handle your user endpoint.  I'm not officially a developer of vouch, but I would imagine that since it isn't a generally available provider, it would need to be added by you either as a PR or as custom updates in your own fork.

**Comment by redm123** [comment]
Thanks for the answer. That was my thought, too. I was just not sure if maybe I'm just holding it wrong ;)

Looks pretty straight forward, so I might try to build a custom provider.

It seems the provider handling is mostly about getting the user info. Would it make sense to add support for some kind of generic provider? Like specify a URL in the config, possibly with some placeholders to fill in some parameters from the authorize step, expect some JSON to be returned and provide some kind of mapping config from JSON fields to User values...?

I mean, instead of people forking and keeping their own provider implementation around, as it's likely not useful for wider consumption. And it's easier to maintain a custom config for some service, than some git branch/fork. I just found https://github.com/vouch/vouch-proxy/issues/139 which seems to handle a similar problem: call some URL and map the returned JSON back to User values.

Just a thought...

**Comment by artagel** [comment]
I'm sure if you submit a PR with a way to handle this in a generic way, it would be welcomed.

**Comment by reedstrm** [comment]
In fact, I've got a PR to support our own local custom OAUTH provider. #141 The primary issue being different userinfo, as you pointed out. Hopefully, that'll help you by example. I didn't try to generalize, since I didn't have more than one data point. If you can come up with something that works for both yours and ours, that might be more general.

**Comment by bnfinet** [comment]
@redm123 I'm inclined to close this issue for the time being, it looks like your question has been answered.  If you would like to submit a PR I'm happy to review.

**Comment by redm123** [comment]
Oh, sorry for not reporting back. So I was able to make it work by hacking an own provider for the user info. Actually I found that our OAuth server is almost like ADFS. I just needed an additional `Authorization` header with client secret for the /token URL. And I get a flat JSON with some custom attributes (see above) instead of a nested id_token.
Not sure how useful that is for public consumption, though...
