### ISSUE TITLE
Auth invalid state when using Docker.alpine on kubernetes

### ISSUE THREAD

**Issue by davidgibbons** [vouch/vouch-proxy#154]
**Use a Paste Service**
https://gist.github.com/davidgibbons/85bf7350632843aec9644d8c1a1e603a

**Describe the problem**
I'm attempting to add vouch to an existing nginx sidecar in my kube setup. We're not using ingresses right now so just adding the annotations for an ingress isn't going to work. 

I feel like i'm pretty close to things working in this setup however after being returned from okta, we're getting in an invalid auth state. 

**Expected behavior**
I would expect after returning from okta, the auth endpoint would have the JWT data and work. 

**Desktop (please complete the following information):**
 - OS: Kubernetes, alpine
 - Browser Chrome
 - Version 76

**Additional context**

**Comment by bnfinet** [comment]
thanks @davidgibbons 

As part of the `/login` flow the a "state" variable is generated and stored in a session cookie in the browser.  After logging in at the IdP (okta), a redirect to the `oauth.callback_url` is issued which includes the "state" var.  `/auth` reads the state variable from the session cookie and makes sure it matches the `state` variable which was handed back by the IdP.  My suspicion is that your browser is not holding the `state` variable stable. 

Are there two state session cookies getting set at the same time?  I wonder if the `favicon.ico` request that the browser is sending is causing two simultaneous requests to `/validate` and causing the session cookie to get overwritten before the round trip to the IdP.

If you look at developer tools and look at the `VouchSession` for every request in the network tab are the cookies the same? 

Is the behavior any different if you give vouch its own domain and setup its own `server {}` block in Nginx?

This 302 redirect back into the same `server` block looks like it should work but its a bit different to the way I have VP setup in my environments...
https://gist.github.com/davidgibbons/85bf7350632843aec9644d8c1a1e603a#file-gistfile1-txt-L139
https://gist.github.com/davidgibbons/85bf7350632843aec9644d8c1a1e603a#file-gistfile1-txt-L108

Could you please supply a complete log from startup.  And could you please show the difference between your `vouch.domains` settings and your `oauth.callback_url` instead of listing all domains as `<redacted>`.  This could be an important distinction.

**Comment by davidgibbons** [comment]
@bnfinet 
I updated the gist with full logs, I didn't realize that they were being truncated due to using a selector.

vouch.domains is set to swagger.vevodev.com, 
callback url is swagger.vevodev.com/auth

**Comment by bnfinet** [comment]
We're talking about this on irc this morning, it might be a bug but we need a bit more information.

The session variable is definitely getting overwritten as all of the requests are redirected to `/login`.  That means any image/css request such as https://swagger.vevodev.com/static/css/main.css gets loaded.

a few questions first...

How is your browser even getting to a page which includes a request to https://swagger.vevodev.com/static/css/main.css without requiring redirection to Vouch Proxy?  If there was a request to https://swagger.vevodev.com/index.html why would it load at all (without redirection to VP) such that the browser would then request https://swagger.vevodev.com/static/css/main.css

Is there another reverse proxy in front of nginx?  If the `server` block for `swagger.vevodev.com` is using `port 8000` why does Vouch Proxy see URLs without `8000` such as  https://swagger.vevodev.com/static/css/main.css or perhaps that config in your gist is not current?

and then can you please try ...

setup `vouch.vevodev.com` and a separate server block for `vouch.vevodev.com` instead of back through `swagger.vevodev.com`

and move `auth_request /validate` to the `server{}` block of swagger.vevodev.com, outside of the `/location` block

I'm curious if that fixes it.

**Comment by davidgibbons** [comment]
There's a ELB doing SSL termination and then the kubernetes cluster maps from the ELB to the target port 8000.

I was really hoping to not have to setup additional domain names to get this to work, my goal was to make a setup pattern that was generic enough that I could use it in front of several different services, adding a vouch-swagger, vouch-app2 is going to be kinda ugly, but i can do it for testing if nothing else.

**Comment by bnfinet** [comment]
this is the question I'm most interested in...

> How is your browser even getting to a page which includes a request to https://swagger.vevodev.com/static/css/main.css without requiring redirection to Vouch Proxy? If there was a request to https://swagger.vevodev.com/index.html why would it load at all (without redirection to VP) such that the browser would then request https://swagger.vevodev.com/static/css/main.css

**Comment by bnfinet** [comment]
All (or a subset) of your sites can 302 redirect to https://vouch.vevodev.com and as long as you set `vouch.domains[0]` to be `vevodev.com` you can use the same pattern in all of your nginx `server{}` blocks for an `$SITE.vevodev.com`.

**Comment by davidgibbons** [comment]
That was my initial (working!) setup but then I was given the specs that they need to backend to different okta apps/groups for different user access.

**Comment by bnfinet** [comment]
Could you please take a moment to answer my question :)

**Comment by davidgibbons** [comment]
Oh sorry, I thought that was more of a rhetorical question. I really don't know. My best guess is that it was cached? I can delete and pull logs again using incognito.

**Comment by bnfinet** [comment]
Is the behavior any different if you evade cache (shift + f5)?

**Comment by davidgibbons** [comment]
Turns out the CSS requests were from the vouch testing mode. 

I needed to add /static to the locations block in nginx.

**Comment by bnfinet** [comment]
So glad to hear it @davidgibbons

Might add something to the documentation incase anyone else cares to setup nginx inline similar to your setup
