### ISSUE TITLE
Multi domain OAuth with GitHub？

### ISSUE THREAD

**Issue by mashirozx** [vouch/vouch-proxy#169]
**First read the README**
Feature Requests

**Describe the problem**
OAuth provider: GitHub

Github can only set one callback URL for each client ID, so the `domains` block in config file won't work (maybe?). But assume there is <http://a.com> and <http://b.com>, I want to use the same OAuth system on both site, can we set two Github client ID for each domain in one vouch progress? Vouch detect the domain, and choose client ID for the domain to certificate.

**Additional context**
Poor English, sorry for ignoring any details in document.

**Comment by bnfinet** [comment]
Vouch Proxy does not have such a feature at this time.  Only one [oauth.provider](https://github.com/vouch/vouch-proxy/blob/master/config/config.yml_example_github#L18-L24) can be configured for each running instance of Vouch Proxy.  You are right, since GitHub only allows one `callback_url` which is set in GitHub's oauth config (or rather,  If provided, the redirect URL's [host and port must exactly match the callback URL](https://developer.github.com/apps/building-oauth-apps/authorizing-oauth-apps/#redirect-urls)) you can only service one domain with `provider: github`.

The memory usage of VP is pretty low by modern standards.  Many folks run multiple Vouch Proxy instances to service multiple domains.  Nginx is a much more capable router and IMHO is the proper level in the stack to do domain routing.

Somewhat as an aside, I've wondered if we should iterate through the list of `callback_urls` (for any provider) and set the VP cookie into each domain listed there.  This presents challenges with `/logout` as well as the cookie domain.  I'm really unsure of the benefits vs a multi VP setup.

I'm going to close this issue but please feel free to ask any further questions you may have.
