### ISSUE TITLE
Does Vouch Proxy support SAML2

### ISSUE THREAD

**Issue by idavollen** [vouch/vouch-proxy#190]
Can Vouch Proxy be used together with KeyCloak that also support _SAML2_ and normal _username/password_ authentication mechanisms?

**Comment by bnfinet** [comment]
VP does not use SAML2, only OAuth / OIDC.

However, there's no reason you can't configure KeyCloak to offer both OIDC and SAML2 in order to support multiple KeyCloak clients... 
https://www.keycloak.org/docs/latest/securing_apps/#supported-protocols
https://stackoverflow.com/questions/54848040/can-oidc-and-saml-work-together-with-keycloak

Does that answer your question @idavollen ?

**Comment by idavollen** [comment]
@bnfinet thanks for your reply. 

I know that KeyCloak can be configured as either as Identity Provider [IdP] or Service Provider [SP] in SAML2. for instance, if my KeyCloak works as SP, under a IdP-Inited SAML2 SSO, the corresponding external IdP will usually POST a SAMLRequest containing SAML Assertion to  the AssertionCustomerAccess on my company, https://www.mycompany.com/saml/sp/profile/post/acs . The post data should be forwarded to vouch-proxy via auth-request /validate on vouch-proxy and vouch-proxy should dispatch it further to my KeyCloak for validating the incoming SAML assertion. I haven't managed to make it work although I tried to set:
`proxy_pass_request_body on;`

**Comment by bnfinet** [comment]
Vouch Proxy uses the OAuth authorization flow such as https://www.oauth.com/oauth2-servers/server-side-apps/example-flow/

VP does not speak SAML and does not pass information on to the IdP.  To login, the end user's browser is 302 redirected to the OAuth login endpoint at the IdP (Keycloak).  None of the content from the initial request is carried in that 302 redirect.
