### ISSUE TITLE
Can Vouch be used for securing APIs

### ISSUE THREAD

**Issue by idavollen** [vouch/vouch-proxy#193]
OAuth2 grant type _client_credentials_ and _password_ can be used for scenario, protecting company's APIs from external access. I am wondering if Vouch can be used in this use case and whether the same settings for vounch in nginx.conf be used?

**Comment by bnfinet** [comment]
The short answer is "No".

Vouch Proxy can be used to protect any http request including api calls, as long as those calls come from a browser which has authenticated via https://vouch.yourdomain.com/login and had the Vouch cookie set there.

Vouch Proxy cannot (or cannot easily) secure server to server api calls since it currently wants to set the cookie.

Another option is to have your api service forward the headers of the request directly to the `/validate` endpoint of VP, just like Nginx does.  If you get `200OK` back then the request is valid.
