### ISSUE TITLE
Config Wrong?

### ISSUE THREAD

**Issue by jessetandor** [vouch/vouch-proxy#195]
Hi, I'm trying to load up vouch via docker and im getting:

**{"level":"fatal","ts":1578490957.7688384,"msg":"Fatal error config file: While parsing config: yaml: unmarshal errors:\n  line 1: cannot unmarshal !!seq into map[string]interface {}"}**

What I'm running to get this errors: https://hasteb.in/onopakum.yaml

Thanks.

**Comment by bnfinet** [comment]
Could you please read the README regarding troubleshooting and submitting
issues.

**Comment by jessetandor** [comment]
Yes, I just did. I've put everything in hastebin (https://hasteb.in/onopakum.yaml). My problem isn't related to anything already mentioned - I haven't got it running yet.

So I guess to be more direct:
1- How can i pass the config file directly to docker. I'm assuming the arg **-v /Users/jesse/Desktop:/config/ \**  is incorrect? 

2- Also what is the **arg -v ${PWD}/data:/data \** - is it mandatory?

Thanks.

**Comment by bnfinet** [comment]
Where on your local filesystem is the config file?  Instead of `-v /Users/jesse/Desktop:/config/` you should put the config in a separate directory and use `-v /path/to/the/vouch/config/directory:/config`

re: `-v ${PWD}/data:/data` `${PWD}` is the environmental variable "Print Working Directory"  and `/data` is the data directory which contains the database.
I'm fairly certain `-v ${PWD}/data:/data` is mandatory, but I could be wrong.

Both `-v /Users/jesse/Desktop:/config/ ` and `-v ${PWD}/data:/data` are `docker run` command line arguments which map the directory from your local filesystem into the docker container's filesystem.

It might be helpful to you to read up on `docker run` and volumes.
https://docs.docker.com/storage/volumes/

https://unix.stackexchange.com/questions/174990/what-is-pwd-vs-current-working-directory 
https://stackoverflow.com/questions/41485217/mount-current-directory-as-a-volume-in-docker-on-windows-10#41489151

**Comment by jessetandor** [comment]
That really helped @bnfinet . It's now running locally but have connectivity issues, will close though, thanks.

**Comment by bnfinet** [comment]
thanks much @jessetandor!  I'm glad it's working.

Best of luck with Vouch Proxy!
