### ISSUE TITLE
How is JWT encoded in the cookie?

### ISSUE THREAD

**Issue by sahuguet** [vouch/vouch-proxy#219]
I finally managed to get vouch-proxy to work with Auth0 sitting on top of SAML (see https://github.com/vouch/vouch-proxy/issues/215).
Now I am trying to have my downstream app to consume some information from JWT.

I assume that the JWT is stored in the cookie.
But when I try to base64 decode the content of the cookie, I am getting garbage.

Is Vouch using a special encoding?

**Comment by bnfinet** [comment]
@sahuguet the Cookie is not just base64 encoded but I'm going to ask you to do your own digging here.

I think you can answer your own question best by taking a look at the code for `/validate` in `handlers.go` and work your way to `cookie.go` and `jwtmanager.go`

VP relies on this package for JWT management.
http://github.com/dgrijalva/jwt-go

**Comment by avishayil** [comment]
I just got here from google searching since I tried to find an easy way to investigate the token.
I wrote a simple python parser tool: https://gist.github.com/avishayil/c6972d7c573032998b753128f2485c66
@bnfinet if you think that's inappropriate (since you sent the OP to do some homework) you can edit / delete my comment.

Thanks

**Comment by avishayil** [comment]
I just got here from google searching since I tried to find an easy way to investigate the token.
I wrote a simple python parser tool for vouch-proxy cookie: https://gist.github.com/avishayil/68a410e47aba108509a424f46506ce4d
@bnfinet if you think that's inappropriate (since you sent the OP to do some homework) you can edit / delete my comment.

Thanks

**Comment by bnfinet** [comment]
@avishayil not inappropriate at all!  Thanks for the contribution.  Would you mind if I linked to it from the README?

**Comment by avishayil** [comment]
> @avishayil not inappropriate at all! Thanks for the contribution. Would you mind if I linked to it from the README?

Of course! Feel free :)
