### ISSUE TITLE
Docker won't run because config file could not be found

### ISSUE THREAD

**Issue by mindfuucker** [vouch/vouch-proxy#238]
Running the docker command in an empty folder results in the following fatal error message: [link](https://hasteb.in/duxaxuhu.json). 

Having the folders pre-made also results in the same result.

Running docker version 19.03.

**Comment by bnfinet** [comment]
Can you please be a bit more specific?  What docker command are you running?

Where is your config file?

**Comment by mindfuucker** [comment]
> What docker command are you running?
The command from [here](https://github.com/vouch/vouch-proxy#running-from-docker), excluding the -d. 

> Where is your config file?
In the container?

**Comment by bnfinet** [comment]
Can you please tell me specifically what you typed into your terminal?

What OS?

Did you create a config file?  Where is it?

**Comment by mindfuucker** [comment]
> Can you please tell me specifically what you typed into your terminal?

[This](https://hasteb.in/rexuviya.nginx)

> What OS?

Ubuntu 19.10

> Did you create a config file?  Where is it?

Where does the Docker installation states that? I did not manual create some sort of config file. Do I need to drop the a .yml file in there?

**Comment by bnfinet** [comment]
Yes, you'll need to create a config.  That's why the conf directory is
mapped in as a volume with '-v'.

Why don't you take a bit of time to try to get VP running with an oauth
provider.  I'm hopeful that you'll be able to get VP running based on
what's in the README and linked resources.  If not, please provide detailed
accounts of your attempts.

If you feel there's an improvement to be made to the documentation then
please do submit a PR.

**Comment by mindfuucker** [comment]
Thank you for being patient with me. 

I will close this case.
