### ISSUE TITLE
After successful login, &lasso-failcount=&X-Vouch-Token=&error=# added to URL

### ISSUE THREAD

**Issue by alexisuk24** [vouch/vouch-proxy#271]
I am using Google Auth

Versions after 0.12.2 (e.g. 0.12.3 and above) are adding the following string to the URL post successful login:

&lasso-failcount=&X-Vouch-Token=&error=#

This is causing some of my websites to return 404 not found or 500 errors.

Version 0.12.2 and prior does not add these tokens to the querystring.

Is this a bug?  If this is a feature, how can I suppress this behavior?

**Comment by bnfinet** [comment]
@alexisuk24 Please update your Nginx config to match the README's 302 redirect.  The name of the project and associated variables were changed in [v0.4.0](https://github.com/vouch/vouch-proxy/tree/v0.4.0#you-should-change-your-config-to-the-new-name-as-of-v040).  Support for the name `lasso` and associated settings is deprecated.

You're seeing the current behavior because of [this change](https://github.com/vouch/vouch-proxy/blob/ab753455d1b1113b6dfa8d1517746408ca0e9164/handlers/login.go#L102).  That could be improved upon but I'm reluctant to call this a bug.

https://github.com/vouch/vouch-proxy/tree/v0.4.0#you-should-change-your-config-to-the-new-name-as-of-v040

**Comment by alexisuk24** [comment]
Hi @bnfinet - I have always used vouch: in my config.yml and am using Docker Hub container voucher/vouch-proxy so do not have visibility into the nginx configuration.  Is this container maintained by this project or a 3rd party?  I'm open to further investigation and understand the reluctance to call this a bug.

**Comment by alexisuk24** [comment]
Also, when comparing 0.12.2 and 0.12.3, it appears that replacing
`urlparam := r.URL.Query().Get("url")`
with 
`urlparam := r.URL.RawQuery`
`urlparam = strings.Split(urlparam, "&vouch-failcount")[0]`
`urlparam = strings.TrimPrefix(urlparam, "url=")`
might have something to do with it?

https://github.com/vouch/vouch-proxy/compare/v0.12.2...v0.12.3

**Comment by bnfinet** [comment]
Yes you are right.  There was a change and that is why you are experiencing
this error/bug.  If you change your nginx config I expect you will not
experience the error/bug.

**Comment by bnfinet** [comment]
@alexisuk24 any progress?  What happens when you update your nginx config?

**Comment by alexisuk24** [comment]
Hi @bnfinet, yes I found the reference to lasso and replaced it with vouch, I no longer see the additional querystring entries post authentication.  Thanks.
