### ISSUE TITLE
requested destination URL has a dangerous query string looks bad: https://xyz.com/ includes https://

### ISSUE THREAD

**Issue by mr-rick** [vouch/vouch-proxy#313]
I get this error with more recent releases of vouch-proxy:

requested destination URL has a dangerous query string looks bad: https://xyz.com/ includes https://

but the redirect urls have https in them... which is how we redirect back to the origin.  Unless I'm missing something here.

**Comment by bnfinet** [comment]
@mr-rick that's a security related change in `v0.11.0`

https://github.com/vouch/vouch-proxy#login-and-logout-endpoint-redirection

If you feel that there's a problem, please post your configs and logs to a gist as per the README.

**Comment by bnfinet** [comment]
@mr-rick if there's no problem to be worked here would you please close this issue?

**Comment by martina-if** [comment]
@bnfinet Hi, we are seeing this issue recently with okta where if someone logs in to okta and then clicks in our okta app they get a redirect with a query param that looks like `?iss=<companyname>.okta.com` and this is considered dangerous by vouch but we cannot change that behaviour in okta. Is there a way to allow-list these query parameters or somehow mitigate this issue?

**Comment by bnfinet** [comment]
@martina-if Hey there!

Is that error at the redirection from okta to the `/auth` endpoint?  If you set `oauth.callback_url` to `https://${VPURL}/auth?iss=yourbiz.okta.com` does that fix it?

**Comment by bnfinet** [comment]
@airpaio thanks for highlighting this in #510

The quickest fix would be to manage the URL explicitly in the 301 redirect in your config...

changing this line
https://gist.github.com/airpaio/ab498461d07bd481a9bdb5a8661e7a48#file-nginx-conf-L30
to

`return 302 http://xxxxxxxxxxxx/vp/login?url=http://YOUR/PREFERRED/ENTRY/POINT/URL&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;`

Otherwise fancier methods of removing the `iss` parameter from the query string may be waranted
https://stackoverflow.com/questions/63054331/nginx-remove-single-query-string-parameter

@martina-if this sounds like the same problem you were having, were you able to resolve your issue?

**Comment by airpaio** [comment]
> The quickest fix would be to manage the URL explicitly in the 301 redirect in your config...
> 
> changing this line https://gist.github.com/airpaio/ab498461d07bd481a9bdb5a8661e7a48#file-nginx-conf-L30 to
> 
> `return 302 http://xxxxxxxxxxxx/vp/login?url=http://YOUR/PREFERRED/ENTRY/POINT/URL&vouch-failcount=$auth_resp_failcount&X-Vouch-Token=$auth_resp_jwt&error=$auth_resp_err;`

Thank you for this suggestion. This quick fix worked for me!

**Comment by bnfinet** [comment]
@flipsed the README shows `nginx.ingress.kubernetes.io/auth-signin` annotation but I'm not a `k8s` user and I'm not really familiar with the VP chart

**Comment by flipsed** [comment]
I got it working now. I needed to modify the ingress on the protected app rather than vouch itself. And indeed I ended up editing the `nginx.ingress.kubernetes.io/auth-signin` annotation instead of adding `nginx.ingress.kubernetes.io/server-snippet`. Thanks for the help!
