### ISSUE TITLE
Reconnect clearing valid cookies

### ISSUE THREAD

**Issue by RishabhAsthana** [vouch/vouch-proxy#334]
First of all, this is a great product! It has been working like a charm for its intended use case. Pretty easy to setup in a HA fashion as well. The issue I am posing is more of a question than an issue.

**Describe the problem**
I was curious about the reasoning behind [clearing cookies](https://github.com/vouch/vouch-proxy/blob/master/handlers/login.go#L39) on any login attempt. In our setup, there is this edge case that seems to be hit and it's hard to reproduce. A lot of traffic is over websockets so our frontends have logic baked in to reconnect periodically if for some reason the socket gets broken. Users have the tendency to leave their dashboards open overnight, well beyond the JWT expiration time so if the socket reconnect is ever attempted, it goes through the OAuth flow and clears out the cookies on the caller's browser. So let's say the user sits down the next day and they login to one of the dashboards. They login successfully and this dashboard works fine for a while, until one of the background tabs issues a reconnect with stale cookies from last day, which Vouch recognizes as bad and initiates login which ends up clearing the good cookies they received in the morning. It's likely a race condition which happens between inflight user login and reconnect before the login succeeds. 

I am thinking of removing the clear cookie logic on login in our local build, but I am unsure about the implications of doing this. Afaik, /logout and /login only clears cookies while /auth sets it. Why _should_ we be clearing cookies if a user shows up with invalid ones?

OAuth provider: Azure AD (also Dex, as a failover option)

**Expected behavior**
The cookies should remain untouched? Given they are invalid, Vouch is not going to let them pass through anyway. I guess having no cookies would make for a fast /validate check, but not sure if that's the reasoning behind clearing them.

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina 10.15.17, Windows 10
 - Browser Chrome 
 - Version 76, 86

**Comment by bnfinet** [comment]
@RishabhAsthana that's an interesting scenario.  I kind of see it both ways...

The general goal of clearing the cookie was to begin with a clean slate before forwarding to the IdP....

In the scenario of `/validate` --> 302 `/login` --> 302 IdP login --> 302 `/auth` --> original destination

The assumption is that the role of `./login` is to prepare for. 

wrt.. 
> I am thinking of removing the clear cookie logic on login in our local build, but I am unsure about the implications of doing this

I'd be curious how that would turn out.  Have you tried it yet?

Another thought is that instead of all of your dashboards using an `@error401` block in nginx that includes `return 302 https://vouch.yourdomain.com/login..` you could redirect them to a different endpoint of your choosing that includes a link to "login here" or something of that nature.

I'm still inclined to clear the cookie at `/login` which feels idempotent to me and more secure.  Those requests are getting forwarded to `/login` because a bad cookie (or no cookie) was presented to `/validate`.  There may be a case to be made with the Chrome team that the browser should be using the most recent cookies when "issuing a reconnect".  

Please do report back here, would love to hear your progress.

**Comment by bnfinet** [comment]
@RishabhAsthana perhaps proxy_hide_header could be used for the /login Set-cookie

http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_hide_header

**Comment by RishabhAsthana** [comment]
@bnfinet Thanks for getting back to me! 
Tbh I haven't been able to reproduce this 100%. I ran some tests and chrome seemed to use the most recent cookies in all cases. The race condition is non-trivial to produce. That said, I removed the logic for clearing cookies (I think the proxy_hide_header you mentioned will achieve the same effect as well without having to touch the code at all) and everything seems to run smoothly without it.

> I'm still inclined to clear the cookie at /login which to me feels idempotent and more secure

Curious about this statement. When you say it's more secure, is it because a careless intruder will end up losing their cookies if end up calling this endpoint directly or indirectly? (It makes sense to me)

**Comment by bnfinet** [comment]
>>  I'm still inclined to clear the cookie at /login which to me feels idempotent and more secure

> Curious about this statement. When you say it's more secure, is it because a careless intruder will end up losing their cookies if end up calling this endpoint directly or indirectly? (It makes sense to me)

It's like if you show up at a bar with an expired ID, the protocol is for the bartender or bouncer to take the ID away in order to get the bad info off the street.  If your jwt/cookie doesn't pass `/validate` then lets clear it out.

> I ran some tests and chrome seemed to use the most recent cookies in all cases

I must be misunderstanding the behavior you're describing. If the most recent cookies are presented, why aren't they passing through `/validate` ?

**Comment by RishabhAsthana** [comment]
Actually, I am not sure if it is only invalid jwt causing. It happens sometimes, the logs indicate either a malformed token was received (gzip errors), and that ends up unsettling the cookies because of re-login. 

I ended up removing that logic for clearing cookies and it has been working fine so far.

Thanks for the help @bnfinet !

**Comment by bnfinet** [comment]
gzip errors seems particularly odd.  I wonder if the nginx buffers should
be opened up a bit.

I'm glad that it's working for you now

**Comment by RishabhAsthana** [comment]
The cookie size is within the 4kb limit. Did a lot of whitelisting on the Azure end to keep the tokens small, but that's a good idea. I shall give it a go. Ended up increasing the expiration time of credentials as well so maybe that's why I am just getting fewer reports.
