### ISSUE TITLE
Does Vouch-proxy offers true SSO (Single Sign On)

### ISSUE THREAD

**Issue by ex0nuss** [vouch/vouch-proxy#357]
Hey there,

I love the Idea of vouch-proxy! But I am kinda confused about it's SSO capabilities.

My homelab is currently running a lot of service with builtin authentication (nextcloud, jellyfin, grafana, ...). My goal is to just login into vouch-proxy and the credentials are piped to the service I wanna access. 
--> So true SSO: One Login, that's it.

Is this somehow possible with VP?

**Comment by aaronpk** [comment]
It depends on the application's ability to accept outside authentication. I use it for basically this, where the backend applications all look for the presence of the HTTP header that Vouch sets to determine the user that is logged in. I'm not sure if NextCloud has a plugin for that, but it'd definitely be possible to create one.

**Comment by ex0nuss** [comment]
Thanks for the quick reply!
I have heard that Nextcloud has an plugin called "social login" for this. I'll take a look at it when I have more spare time :)
Is this also possible with basic auth for legacy services?

**Comment by aaronpk** [comment]
Vouch isn't a traditional IdP itself, although it would certainly be interesting to explore that idea. The backend applications that Vouch protects typically either don't have a concept of users (protect some sort of otherwise public dashboard), or can be configured to look for an HTTP header from the proxy and use that to sort of "force" the logged-in state in the application, e.g. the [remoteuser MediaWiki plugin](https://www.mediawiki.org/wiki/Extension:Auth_remoteuser). You'd need to find an extension for NextCloud like that.

**Comment by ex0nuss** [comment]
Thanks so much for all the ideas! 
I am already using the protecting public dashboards concept and it works great so far. I'll dig the internet to find something like that! :D

**Comment by bnfinet** [comment]
@ex0nuss Thanks for the kind words.  I'm going to close this but feel free to ask more questions here if there's anything else we can help with.

**Comment by bnfinet** [comment]
@aaronpk I hadn't seen the MediaWiki plugin before!  Are there other's that you know of?  Is it worth carrying a list in the README?

**Comment by aaronpk** [comment]
a list in the readme is definitely a good idea!

**Comment by bnfinet** [comment]
@aaronpk do you have any others?  A list of three seems more appealing than a list of one :)
