### ISSUE TITLE
Passing a Basic Auth or other `Authorization` header to a backend service (Kibana and Elastic Search) after clearing Vouch Proxy

### ISSUE THREAD

**Issue by manavkapoor** [vouch/vouch-proxy#360]
I'm fronting Kibana (Elasticsearch UI) with Vouch and it's working just fine getting to the Kibana login page. Issue is I'm try to bypass the login page and the known way to do that is to pass a basic authorization header to Kibana. I've had issues trying to send an authorization header in addition to the Vouch cookie. I receive 403 Forbidden errors. The logs show that Vouch was able to authenticate successfully but it immediately returns 403 when attempting to redirect back to the app page. The credentials that Kibana need are unique from oidc (Okta) which is why we need creds than what can get from Vouch. Below is where I've been attempting to send the header to the Kibana backend.

```    location / {
        auth_request                 /vouch-validate;

        proxy_set_header X-Vouch-User $auth_user;
        proxy_pass_request_headers on;

# attempt 1 of sending the header to the backend 
        proxy_set_header Authorization "Basic ${es_kibana_basic_auth}"; 

        proxy_pass http://backend;

# attempt 2 of sending the header to the backend
        # more_set_input_headers 'Authorization: Basic ${es_kibana_basic_auth}';
        # more_set_headers -s 401 'WWW-Authenticate: Basic realm="backend"';

    }
```

Are there any clever ways of being able to pass these creds to the backend or should I be going about it a different way? To reinterate, these creds are not available at the Okta scope/claim level and are unique to the app (Kibana/Elasticsearch) which is why I am going about it this way. This method has worked for other proxies we have used (https://github.com/pinepain/ldap-auth-proxy). 

Thanks, and kudos to building such a great proxy.

**Comment by bnfinet** [comment]
@manavkapoor thanks for the kind words

I think you're on the right track but I don't see a clear path to putting an `Authorization: Basic ...` header in place.

The RFC[1] of course specifes that the `id:password` portion of `Authorization: Basic realm="backend" bnfinet:supersecret` should be base64 encoded.   

Nginx does not include a facility for base64 encoding.  There is a module which might help to perform the base64 encoding, though you'd need to compile your own Nginx to include the module.

I'm unsure if there's a strong argument to be made for a new VP feature to return a base64 of `userid:pass` back as a basic auth.  And really that's likely to include just a dummy password since it would be unusual for an OAuth provider to offer a password instead of a token. 

There's a bit of a hack that may work though...
You could add a header to the downstream request to Kibana/ES which includes `Authorization: ApiKey $KEY` [3].  This would require generating a key directly with Kibana/ES [4] (perhaps via curl) and then adding it to Nginx. 

I hope that is helpful, do chime back here to 

[1] https://tools.ietf.org/html/rfc7617
[2] https://github.com/timebug/base64-nginx-module
[3] https://www.elastic.co/guide/en/elasticsearch/reference/7.11/token-authentication-services.html see "api-key-service"
[4] https://www.elastic.co/guide/en/elasticsearch/reference/7.11/security-api-create-api-key.html

**Comment by manavkapoor** [comment]
I appreciate the suggestions! Turns out it was a bug with our nginx configuration. You can totally pass base64 headers via nginx without the base64 specific module as seen below:

```
              location / {
                  auth_request /vouch-validate;
                  proxy_set_header X-Vouch-User $auth_user;
                  proxy_pass_request_headers on;
                  proxy_set_header  Authorization "Basic ${es_kibana_basic_auth}";
                  proxy_pass http://backend;
              }
```
I love the proxy and I'm so happy it worked. Cheers!

**Comment by bnfinet** [comment]
@manavkapoor I'm so glad to hear that!

Just to clarify, in that snippet you're passing a preconfigured (dummy) `user:pass` in `${es_kibana_basic_auth}`, is that right?  `${es_kibana_basic_auth}` isn't user specific?

**Comment by maxxer** [comment]
@manavkapoor sorry for rising an old discussion, but I'm attempting to do the same and I was wondering where do you set the `${es_kibana_basic_auth}` variable from. If you can share your full config/setup it would be great. Thank you.
