### ISSUE TITLE
build error: go get cannot find package

### ISSUE THREAD

**Issue by o0laxkilla0o** [vouch/vouch-proxy#361]
running ./do.sh get the following error package github.com/hashicorp/hcl/hcl/printer: cannot find package

**Comment by bnfinet** [comment]
@o0laxkilla0o thanks for the report

This is the underlying issue.
https://github.com/spf13/viper/issues/1076

The fix is to use [Golang modules](https://golang.org/ref/mod) which I have been remiss to do (I am a jilted lover).  Golang modules can be problematic when forking and building the software, has been an unstable api having changed significantly twice in three years and just generally still has warts.

But that (`go mod init`) looks like it fixes the issue.

I have something that works locally (little more than that) but it requires further testing.

**Comment by o0laxkilla0o** [comment]
I don't mean to be a bother but I am assuming I have to wait till you make a change on your end before I can build this correct?

**Comment by bnfinet** [comment]
Well, you could download a Docker container which includes the prebuilt
binary and then 'docker cp /path/to/vouch/proxy ./'

But I'm not in a position to look at that closely at the moment.  :)

Otherwise yes, this will need to wait til early next week.

**Comment by rajendrarusmana** [comment]
Hi, I tried just adding one line in do.sh `export GO111MODULES=on` and that seems to do the trick. Would this be acceptable as a pull request or just in a branch in this repo? Because one of our applications has a broken build due to this and if possible we would try to avoid forking.

**Comment by bnfinet** [comment]
Unfortunately while that is a quick fix that's kicking the can down the
road.

It's time for 'go mod init' and 'go mod tidy'.  Might as well jump in with
both feet.

Thanks nonetheless, that's a good data point.

(And it's casein point of the warts of the go modules system.)
