### ISSUE TITLE
Authenticating a python script

### ISSUE THREAD

**Issue by swhitman0** [vouch/vouch-proxy#446]
Hello,

We use vouch-proxy to authenticate a web application. However, besides running the web application in a browser, we need to access some API endpoints programmatically from a Jupyter notebook. How can a python script authenticate a user to an API protected with vouch-proxy?

Thanks

**Comment by bnfinet** [comment]
@swhitman0 ...

if the script will run from within the network local to your protected API you could use `satisfy any` as per https://github.com/vouch/vouch-proxy/issues/378#issuecomment-814423460

Otherwise it's going to have to wait for either #362 or perhaps #422 to be implemented.

> How can a python script authenticate a user

If you do need a user to be specified you may want to populate the `X-Vouch-User` header to mimic the header that VP adds

**Comment by swhitman0** [comment]
@bnfinet ...

Thanks for the response. 

We were wondering if the device code flow could be used? (https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-device-code) We have successfully used the MSAL python library to authenticate using the device code flow, but we are at a loss as to what to do with the token returned by the flow.

**Comment by bnfinet** [comment]
@swhitman0 VP does not support the device code flow
