### ISSUE TITLE
do.sh build requires a git repository

### ISSUE THREAD

**Issue by isomc-stone** [vouch/vouch-proxy#447]
pulled a zip from the [releases tags](https://github.com/vouch/vouch-proxy/tags)

when I ran `./do.sh build` I got

> fatal: Not a valid object name HEAD
> fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
> Use '--' to separate paths from revisions, like this:
> 'git <command> [<revision>...] -- [<file>...]'

workaround:

make a git repo

```bash
git init
git add .
git commit -a -m'whatever'
./do.sh build
````

**Comment by bnfinet** [comment]
thanks @isomc-stone thanks for the report and documenting this work around.  I think I'm willing to live with that limitation.

Another option is to run `go build .` instead of `./do.sh build`, essentially just removing the `-ldflags` directives.
https://github.com/vouch/vouch-proxy/blob/master/do.sh#L32

For bug reports and other support aspects I like to have the tag and build information included in the binary, since it gets printed to the logs at startup.  I'm reluctant to document/support something that doesn't include that info.

I'm going to close this.  If someone else reports something similar I'll push them towards this issue.  If at some point we do get a number of reports perhaps it will be worthy of considering in earnest.

Cheers!
