### ISSUE TITLE
Possible to retreieve profile information such as profile picture after logging in?

### ISSUE THREAD

**Issue by SohMahmood** [vouch/vouch-proxy#455]
I have got vouch working with Google Auth and would like to show the profile picture of the client on the top right after they login. Would there be any way for JavaScript to get this information?

**Comment by bnfinet** [comment]
@SohMahmood it can be done with some setup.

You'll need to look at custom claims and how to get the picture returned by Google into an HTTP header.  I don't have enough time today to look up the specifics.

After you pass the header to your app you'll need to use [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch) to make another request to the webserver so that you can retrieve the headers.  You'll want to do that with `credentials: 'include'` so that the VP cookies and JWT is passed with the request.

That will give you the URL.

There may also be a way to get it directly from the VP cookies but VP cookies can be complex to reassemble into a JWT, decompress, decrypt and parse.  This should be much more reliable.

I'm going to close this for now but please do report back with your progress.
