### ISSUE TITLE
Vouch-Proxy High Availability

### ISSUE THREAD

**Issue by artagel** [vouch/vouch-proxy#93]
How are you handling HA for vouch?  
If I run this in a docker host scaled out to 3, for example...each would have it's own database, and since the database isn't capable of multi-access on a shared volume, we can't share it.

Would a user that hasn't "hit" that vouch instance simply redirect to the auth server and then redirect back since they have a single sign on cookie from that service, which would then transparently give the user a vouch cookie and forward them on their merry way?  Or would they need to auth again at the auth server(let's say keycloak or google).

**Comment by bnfinet** [comment]
I think of it in the context of the nginx deployment.

if configured with the same secret, each deployed Vouch Proxy instance will be able to `/validate` properly and can support a deployed nginx or app.

Since the `/login` --> IdP --> `/auth` cycle is infrequent you can have just one or two instances of `vouch.yourdomain.com` running and it should be fine.

The DB really isn't used for much at this point, just accounting.  Doesn't even really need to be shared.

**Comment by artagel** [comment]
Yea, that makes sense, I figured it would work similarly.
I'm essentially scaling this internal app in a swarm, with 3 nginx LB to Vouch (also scaled to 3) as well as the other services I'm exposing throug nginx.  I'll be testing this fully soon, hopefully :)

**Comment by bnfinet** [comment]
Best of luck!

The best visibility for a HA Vouch setup is log aggregation.  If you're running multiple Vouch Proxies in your environment and capturing the logs I'd love to hear how that's working out.  One of the goals with the logging branch is to capture metrics in consistent units and rely on structured logs a bit more.

I do see a point where a shared DB will be necessary (or at least desirable) for Vouch Proxy.  But its going to be a bit before that happens.
